# Generated by Django 5.0.4 on 2024-06-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_measure_custom_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUnitOfMeasure',
        ),
    ]
